BACKGROUND_COLOR = (0, 0, 0)  # Colors.black
DATETIME_FORMAT = "%Y%m%d_%H%M%S_%f"
DEFAULT_IMAGE_SIZE = (1080, 1080)
IMAGE_DIRECTORY_NAME = 'files'
IMAGE_FORMAT_COLOR_MODE = 'RGB'
IMAGE_FORMAT = 'jpeg'
IMAGE_EXTENSION = 'jpeg'


# Video settings
BITRATE = 3000
FRAMES_PER_SECOND = 30
VIDEO_EXTENSION = 'mp4'
VIDEO_CODEC = 'libx264'
VIDEO_PIXEL_FORMAT = 'yuv420p'
